[2022-02-01 05:57:13,952] {processor.py:163} INFO - Started process (PID=3858) to work on /opt/airflow/dags/local.py
[2022-02-01 05:57:13,959] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 05:57:13,967] {logging_mixin.py:109} INFO - [2022-02-01 05:57:13,965] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 05:57:14,327] {logging_mixin.py:109} INFO - [2022-02-01 05:57:14,313] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2022-02-01 05:57:14,385] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 05:57:14,450] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.541 seconds
[2022-02-01 05:57:44,798] {processor.py:163} INFO - Started process (PID=3887) to work on /opt/airflow/dags/local.py
[2022-02-01 05:57:44,916] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 05:57:44,926] {logging_mixin.py:109} INFO - [2022-02-01 05:57:44,926] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 05:57:45,016] {logging_mixin.py:109} INFO - [2022-02-01 05:57:45,009] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2022-02-01 05:57:45,194] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 05:57:45,227] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.444 seconds
[2022-02-01 05:58:15,362] {processor.py:163} INFO - Started process (PID=3907) to work on /opt/airflow/dags/local.py
[2022-02-01 05:58:15,366] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 05:58:15,369] {logging_mixin.py:109} INFO - [2022-02-01 05:58:15,368] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 05:58:15,397] {logging_mixin.py:109} INFO - [2022-02-01 05:58:15,394] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2022-02-01 05:58:15,428] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 05:58:15,447] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.091 seconds
[2022-02-01 05:58:45,514] {processor.py:163} INFO - Started process (PID=3927) to work on /opt/airflow/dags/local.py
[2022-02-01 05:58:45,524] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 05:58:45,526] {logging_mixin.py:109} INFO - [2022-02-01 05:58:45,526] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 05:58:45,557] {logging_mixin.py:109} INFO - [2022-02-01 05:58:45,551] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2022-02-01 05:58:45,592] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 05:58:45,612] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.103 seconds
[2022-02-01 05:59:15,996] {processor.py:163} INFO - Started process (PID=3948) to work on /opt/airflow/dags/local.py
[2022-02-01 05:59:16,003] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 05:59:16,007] {logging_mixin.py:109} INFO - [2022-02-01 05:59:16,006] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 05:59:16,051] {logging_mixin.py:109} INFO - [2022-02-01 05:59:16,046] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2022-02-01 05:59:16,117] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 05:59:16,142] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.155 seconds
[2022-02-01 05:59:46,615] {processor.py:163} INFO - Started process (PID=3968) to work on /opt/airflow/dags/local.py
[2022-02-01 05:59:46,631] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 05:59:46,638] {logging_mixin.py:109} INFO - [2022-02-01 05:59:46,636] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 05:59:46,812] {logging_mixin.py:109} INFO - [2022-02-01 05:59:46,809] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2022-02-01 05:59:46,850] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 05:59:46,883] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.276 seconds
[2022-02-01 06:20:41,479] {processor.py:163} INFO - Started process (PID=579) to work on /opt/airflow/dags/local.py
[2022-02-01 06:20:41,482] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:20:41,485] {logging_mixin.py:109} INFO - [2022-02-01 06:20:41,485] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:20:41,624] {logging_mixin.py:109} INFO - [2022-02-01 06:20:41,613] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:20:41,667] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:20:41,703] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.232 seconds
[2022-02-01 06:21:12,425] {processor.py:163} INFO - Started process (PID=599) to work on /opt/airflow/dags/local.py
[2022-02-01 06:21:12,431] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:21:12,444] {logging_mixin.py:109} INFO - [2022-02-01 06:21:12,442] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:21:12,540] {logging_mixin.py:109} INFO - [2022-02-01 06:21:12,519] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:21:12,607] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:21:12,662] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.260 seconds
[2022-02-01 06:21:43,829] {processor.py:163} INFO - Started process (PID=620) to work on /opt/airflow/dags/local.py
[2022-02-01 06:21:43,863] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:21:43,875] {logging_mixin.py:109} INFO - [2022-02-01 06:21:43,868] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:21:44,109] {logging_mixin.py:109} INFO - [2022-02-01 06:21:44,074] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:21:44,286] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:21:44,516] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.727 seconds
[2022-02-01 06:22:14,833] {processor.py:163} INFO - Started process (PID=632) to work on /opt/airflow/dags/local.py
[2022-02-01 06:22:14,839] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:22:14,844] {logging_mixin.py:109} INFO - [2022-02-01 06:22:14,844] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:22:14,888] {logging_mixin.py:109} INFO - [2022-02-01 06:22:14,878] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:22:14,951] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:22:14,979] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.153 seconds
[2022-02-01 06:27:29,262] {processor.py:163} INFO - Started process (PID=66) to work on /opt/airflow/dags/local.py
[2022-02-01 06:27:29,276] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:27:29,285] {logging_mixin.py:109} INFO - [2022-02-01 06:27:29,283] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:27:29,482] {logging_mixin.py:109} INFO - [2022-02-01 06:27:29,463] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:27:29,527] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:27:29,552] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.311 seconds
[2022-02-01 06:28:00,262] {processor.py:163} INFO - Started process (PID=87) to work on /opt/airflow/dags/local.py
[2022-02-01 06:28:00,272] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:28:00,275] {logging_mixin.py:109} INFO - [2022-02-01 06:28:00,275] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:28:00,383] {logging_mixin.py:109} INFO - [2022-02-01 06:28:00,363] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:28:00,531] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:28:00,965] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.725 seconds
[2022-02-01 06:28:31,772] {processor.py:163} INFO - Started process (PID=99) to work on /opt/airflow/dags/local.py
[2022-02-01 06:28:31,787] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:28:31,799] {logging_mixin.py:109} INFO - [2022-02-01 06:28:31,795] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:28:31,911] {logging_mixin.py:109} INFO - [2022-02-01 06:28:31,891] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:28:31,968] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:28:32,030] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.328 seconds
[2022-02-01 06:29:02,286] {processor.py:163} INFO - Started process (PID=116) to work on /opt/airflow/dags/local.py
[2022-02-01 06:29:02,292] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:29:02,297] {logging_mixin.py:109} INFO - [2022-02-01 06:29:02,296] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:29:02,357] {logging_mixin.py:109} INFO - [2022-02-01 06:29:02,342] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:29:02,430] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:29:02,470] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.195 seconds
[2022-02-01 06:29:33,531] {processor.py:163} INFO - Started process (PID=145) to work on /opt/airflow/dags/local.py
[2022-02-01 06:29:33,629] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:29:33,633] {logging_mixin.py:109} INFO - [2022-02-01 06:29:33,633] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:29:33,847] {logging_mixin.py:109} INFO - [2022-02-01 06:29:33,818] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:29:33,980] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:29:34,661] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 1.195 seconds
[2022-02-01 06:30:06,708] {processor.py:163} INFO - Started process (PID=155) to work on /opt/airflow/dags/local.py
[2022-02-01 06:30:06,711] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:30:06,713] {logging_mixin.py:109} INFO - [2022-02-01 06:30:06,713] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:30:06,756] {logging_mixin.py:109} INFO - [2022-02-01 06:30:06,750] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:30:06,793] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:30:06,814] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.112 seconds
[2022-02-01 06:30:37,925] {processor.py:163} INFO - Started process (PID=175) to work on /opt/airflow/dags/local.py
[2022-02-01 06:30:37,929] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:30:37,932] {logging_mixin.py:109} INFO - [2022-02-01 06:30:37,932] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:30:38,076] {logging_mixin.py:109} INFO - [2022-02-01 06:30:38,065] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 14, in <module>
    bash_command='echo "hello world"'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 683, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 789, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 840, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2139, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2022-02-01 06:30:38,119] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:30:38,197] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.293 seconds
[2022-02-01 06:30:51,322] {processor.py:163} INFO - Started process (PID=185) to work on /opt/airflow/dags/local.py
[2022-02-01 06:30:51,338] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:30:51,352] {logging_mixin.py:109} INFO - [2022-02-01 06:30:51,351] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:30:51,497] {logging_mixin.py:109} INFO - [2022-02-01 06:30:51,463] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 9
    start_date=datetime(2021, 1, 1)
             ^
SyntaxError: invalid syntax
[2022-02-01 06:30:51,613] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:30:51,642] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.388 seconds
[2022-02-01 06:31:05,665] {processor.py:163} INFO - Started process (PID=186) to work on /opt/airflow/dags/local.py
[2022-02-01 06:31:05,672] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:31:05,676] {logging_mixin.py:109} INFO - [2022-02-01 06:31:05,676] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:31:05,713] {logging_mixin.py:109} INFO - [2022-02-01 06:31:05,711] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/local.py", line 9
    start_date=datetime(2021, 1, 1)
             ^
SyntaxError: invalid syntax
[2022-02-01 06:31:05,788] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:31:05,817] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.160 seconds
[2022-02-01 06:31:15,831] {processor.py:163} INFO - Started process (PID=196) to work on /opt/airflow/dags/local.py
[2022-02-01 06:31:15,841] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:31:15,846] {logging_mixin.py:109} INFO - [2022-02-01 06:31:15,846] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:31:16,065] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:31:44,768] {logging_mixin.py:109} INFO - [2022-02-01 06:31:44,768] {manager.py:496} INFO - Created Permission View: can edit on DAG:LocalIngestionDag
[2022-02-01 06:31:44,833] {logging_mixin.py:109} INFO - [2022-02-01 06:31:44,832] {manager.py:496} INFO - Created Permission View: can read on DAG:LocalIngestionDag
[2022-02-01 06:31:44,840] {logging_mixin.py:109} INFO - [2022-02-01 06:31:44,835] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:31:44,889] {logging_mixin.py:109} INFO - [2022-02-01 06:31:44,889] {dag.py:2415} INFO - Creating ORM DAG for LocalIngestionDag
[2022-02-01 06:31:44,934] {logging_mixin.py:109} INFO - [2022-02-01 06:31:44,933] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2022-02-01 06:31:45,000] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 29.219 seconds
[2022-02-01 06:32:15,872] {processor.py:163} INFO - Started process (PID=245) to work on /opt/airflow/dags/local.py
[2022-02-01 06:32:15,878] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:32:15,881] {logging_mixin.py:109} INFO - [2022-02-01 06:32:15,880] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:32:16,015] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:32:16,050] {logging_mixin.py:109} INFO - [2022-02-01 06:32:16,050] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:32:16,119] {logging_mixin.py:109} INFO - [2022-02-01 06:32:16,119] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2022-02-01 06:32:16,139] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.287 seconds
[2022-02-01 06:32:19,741] {processor.py:163} INFO - Started process (PID=246) to work on /opt/airflow/dags/local.py
[2022-02-01 06:32:19,783] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:32:19,788] {logging_mixin.py:109} INFO - [2022-02-01 06:32:19,787] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:32:20,322] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:32:20,367] {logging_mixin.py:109} INFO - [2022-02-01 06:32:20,367] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:32:20,423] {logging_mixin.py:109} INFO - [2022-02-01 06:32:20,423] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2022-02-01 06:32:20,828] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 1.192 seconds
[2022-02-01 06:32:51,912] {processor.py:163} INFO - Started process (PID=257) to work on /opt/airflow/dags/local.py
[2022-02-01 06:32:51,915] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:32:51,918] {logging_mixin.py:109} INFO - [2022-02-01 06:32:51,917] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:32:52,198] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:32:52,265] {logging_mixin.py:109} INFO - [2022-02-01 06:32:52,264] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:32:52,328] {logging_mixin.py:109} INFO - [2022-02-01 06:32:52,328] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2022-02-01 06:32:52,404] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.498 seconds
[2022-02-01 06:33:22,553] {processor.py:163} INFO - Started process (PID=277) to work on /opt/airflow/dags/local.py
[2022-02-01 06:33:22,576] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:33:22,591] {logging_mixin.py:109} INFO - [2022-02-01 06:33:22,591] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:33:22,798] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:33:22,851] {logging_mixin.py:109} INFO - [2022-02-01 06:33:22,850] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:33:22,899] {logging_mixin.py:109} INFO - [2022-02-01 06:33:22,899] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2022-02-01 06:33:22,917] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.383 seconds
[2022-02-01 06:33:53,115] {processor.py:163} INFO - Started process (PID=297) to work on /opt/airflow/dags/local.py
[2022-02-01 06:33:53,121] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:33:53,126] {logging_mixin.py:109} INFO - [2022-02-01 06:33:53,125] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:33:53,202] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:33:53,225] {logging_mixin.py:109} INFO - [2022-02-01 06:33:53,225] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:33:53,258] {logging_mixin.py:109} INFO - [2022-02-01 06:33:53,258] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2022-02-01 06:33:53,299] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.194 seconds
[2022-02-01 06:34:07,687] {processor.py:163} INFO - Started process (PID=308) to work on /opt/airflow/dags/local.py
[2022-02-01 06:34:07,702] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:34:07,712] {logging_mixin.py:109} INFO - [2022-02-01 06:34:07,711] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:34:08,233] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:34:11,987] {logging_mixin.py:109} INFO - [2022-02-01 06:34:11,987] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:34:12,114] {logging_mixin.py:109} INFO - [2022-02-01 06:34:12,114] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-01-02 06:00:00+00:00
[2022-02-01 06:34:12,155] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 4.507 seconds
[2022-02-01 06:34:42,495] {processor.py:163} INFO - Started process (PID=327) to work on /opt/airflow/dags/local.py
[2022-02-01 06:34:42,506] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:34:42,530] {logging_mixin.py:109} INFO - [2022-02-01 06:34:42,529] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:34:43,017] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:34:43,120] {logging_mixin.py:109} INFO - [2022-02-01 06:34:43,119] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:34:43,335] {logging_mixin.py:109} INFO - [2022-02-01 06:34:43,334] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2021-09-02T06:00:00+00:00
[2022-02-01 06:34:43,404] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 0.949 seconds
[2022-02-01 06:35:16,060] {processor.py:163} INFO - Started process (PID=337) to work on /opt/airflow/dags/local.py
[2022-02-01 06:35:16,500] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:35:16,873] {logging_mixin.py:109} INFO - [2022-02-01 06:35:16,873] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:35:21,266] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:35:21,752] {logging_mixin.py:109} INFO - [2022-02-01 06:35:21,724] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:35:23,269] {logging_mixin.py:109} INFO - [2022-02-01 06:35:23,264] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2022-01-02T06:00:00+00:00
[2022-02-01 06:35:23,491] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 7.649 seconds
[2022-02-01 06:35:55,509] {processor.py:163} INFO - Started process (PID=357) to work on /opt/airflow/dags/local.py
[2022-02-01 06:35:55,554] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:35:55,590] {logging_mixin.py:109} INFO - [2022-02-01 06:35:55,589] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:35:56,674] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:35:57,349] {logging_mixin.py:109} INFO - [2022-02-01 06:35:57,349] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:35:58,607] {logging_mixin.py:109} INFO - [2022-02-01 06:35:58,607] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2022-01-02T06:00:00+00:00
[2022-02-01 06:35:58,865] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 3.455 seconds
[2022-02-01 06:36:30,366] {processor.py:163} INFO - Started process (PID=376) to work on /opt/airflow/dags/local.py
[2022-02-01 06:36:30,393] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:36:30,489] {logging_mixin.py:109} INFO - [2022-02-01 06:36:30,488] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:36:33,521] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:36:33,928] {logging_mixin.py:109} INFO - [2022-02-01 06:36:33,928] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:36:34,693] {logging_mixin.py:109} INFO - [2022-02-01 06:36:34,680] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2022-01-02T06:00:00+00:00
[2022-02-01 06:36:36,347] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 6.387 seconds
[2022-02-01 06:37:11,881] {processor.py:163} INFO - Started process (PID=395) to work on /opt/airflow/dags/local.py
[2022-02-01 06:37:11,909] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:37:11,973] {logging_mixin.py:109} INFO - [2022-02-01 06:37:11,970] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:37:13,148] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:37:13,800] {logging_mixin.py:109} INFO - [2022-02-01 06:37:13,800] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:37:15,145] {logging_mixin.py:109} INFO - [2022-02-01 06:37:15,145] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2022-01-02T06:00:00+00:00
[2022-02-01 06:37:16,632] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 5.018 seconds
[2022-02-01 06:37:53,576] {processor.py:163} INFO - Started process (PID=416) to work on /opt/airflow/dags/local.py
[2022-02-01 06:37:53,635] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:37:53,645] {logging_mixin.py:109} INFO - [2022-02-01 06:37:53,645] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:37:54,579] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:37:54,865] {logging_mixin.py:109} INFO - [2022-02-01 06:37:54,865] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:37:55,854] {logging_mixin.py:109} INFO - [2022-02-01 06:37:55,854] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2022-01-02T06:00:00+00:00
[2022-02-01 06:37:56,254] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 3.258 seconds
[2022-02-01 06:38:28,213] {processor.py:163} INFO - Started process (PID=438) to work on /opt/airflow/dags/local.py
[2022-02-01 06:38:28,269] {processor.py:642} INFO - Processing file /opt/airflow/dags/local.py for tasks to queue
[2022-02-01 06:38:28,326] {logging_mixin.py:109} INFO - [2022-02-01 06:38:28,324] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/local.py
[2022-02-01 06:38:29,761] {processor.py:654} INFO - DAG(s) dict_keys(['LocalIngestionDag']) retrieved from /opt/airflow/dags/local.py
[2022-02-01 06:38:29,973] {logging_mixin.py:109} INFO - [2022-02-01 06:38:29,971] {dag.py:2396} INFO - Sync 1 DAGs
[2022-02-01 06:38:30,429] {logging_mixin.py:109} INFO - [2022-02-01 06:38:30,423] {dag.py:2935} INFO - Setting next_dagrun for LocalIngestionDag to 2022-01-02T06:00:00+00:00
[2022-02-01 06:38:30,825] {processor.py:171} INFO - Processing /opt/airflow/dags/local.py took 3.003 seconds
